---
# The top level `integrations` list contains the distinct test setups
# Each integration is a distinct container run - the configured dependencies are deployed, the manifest applied and the tests run
# All paths should be relative to the location of the specs file
integrations:
- name: exporter-tests
  manifest: site-exporters.pp
  fixtures:
    modules:
      - name: prometheus
        path: ../../prometheus
    files:
      - files/test1
      - files/test2
  goss-tests:
    user:
      prometheus:
        exists: true
        groups:
          - prometheus
        home: /home/prometheus
        shell: /sbin/nologin
- name: server-tests
  manifest: site-server.pp
  fixtures:
    modules:
      - name: prometheus
        path: ../../prometheus
    files:
  goss-tests:
    file:
      /home/prometheus/prometheus-2.27.1.linux-amd64/prometheus:
        exists: true
        mode: "0755"
        filetype: file
...